#ifndef I_PREFIX_REGISTER_PROXY_CONFIG_H
#define I_PREFIX_REGISTER_PROXY_CONFIG_H

// To be implemented
#define IDNS_TRUST_ANCHOR "88888888"
#define IDNS_ROOT_TOKEN 31
#define IDNS_ROOT_ENTITY_ID 66

// DNS
#define RESPONSIBLE_ZONE ""

// network
#define TEST_DOMAIN_ADMIN "192.168.66.107"
#define REMOTE_PORT 1038

#define LOCAL_IGATE_IP "192.168.66.1"

// global database
#define PREFIX_TREE_ROOT "/"
#define MAX_PTNODE_CHILDREN_NUM  256
#define MAX_PTNODE_DEPTH  10
#define MAX_PTNODE_WIDTH  8192
#define PT_DEBUG
#define EIT_DEBUG

#endif